### ISSUE TITLE
Building v4.0.2 and v4.0.1 error Cannot find name 'Awaited'.

### ISSUE THREAD

**Issue by asghaier76** [ProjectOpenSea/opensea-js#580]
I am trying to use the latest versions v4.0.2 and v4.0.1 but when building getting the following error

Error: node_modules/@opensea/seaport-js/lib/types.d.ts:128:101 - error TS2304: Cannot find name 'Awaited'.

128 export declare type ContractMethodReturnType<T extends Contract, U extends keyof T["callStatic"]> = Awaited<ReturnType<T["callStatic"][U]>>;
                                                   
Environment
Angular 12
Node v16.14.2

**Comment by ZeroSkill830** [comment]
Same issue with Angular 13 and typescript 4.4.3

**Comment by asghaier76** [comment]
> Same issue with Angular 13 and typescript 4.4.3

I was planning to upgrade to Angular 13, but did you try typescript 4.5.x I read that Awaited was introduced in typescript 4.5
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html

**Comment by ZeroSkill830** [comment]
> > Same issue with Angular 13 and typescript 4.4.3
> 
> I was planning to upgrade to Angular 13, but did you try typescript 4.5.x I read that Awaited was introduced in typescript 4.5 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html

I've upgraded to 14 that supports Typescript > 4.6.0 and it works

**Comment by asghaier76** [comment]
@ZeroSkill830 do you have an issue with your build related to this https://github.com/ProjectOpenSea/opensea-js/issues/451
if you faced an issue with that would you mind to share how you resolve it

**Comment by ZeroSkill830** [comment]
> @ZeroSkill830 do you have an issue with your build related to this #451 if you faced an issue with that would you mind to share how you resolve it

I didn't have any issues after upgrading to 14,

**Comment by asghaier76** [comment]
Upgrading angular and typescript solved this issue
