### ISSUE TITLE
Since Upgrade to 3.0.0  TypeError: supportedProvider.send.toString(...).replaceAll is not a function

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#430]
I just upgraded to 3.0.0 and also tested with 3.0.1 since then my app does not start up anymore. 

Errors I am getting 
`|     at Object.standardizeOrThrow (/app/node_modules/@0x/web3-wrapper/node_modules/@0x/utils/src/provider_utils.ts:78:71)
nftapi_1    |     at new Web3Wrapper (/app/node_modules/@0x/web3-wrapper/src/web3_wrapper.ts:157:40)
nftapi_1    |     at new WyvernProtocol (/app/node_modules/wyvern-js/src/wyvernProtocol.ts:397:25)
nftapi_1    |     at new OpenSeaPort (/app/node_modules/opensea-js/src/seaport.ts:201:28)
nftapi_1    |     at new UpdateCollectionService (/app/src/modules/collection/service/update_collection.service.ts:32:20)
nftapi_1    |     at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:329:19)
nftapi_1    |     at callback (/app/node_modules/@nestjs/core/injector/injector.js:48:41)
nftapi_1    |     at Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:122:24)
nftapi_1    |     at Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:52:9)
nftapi_1    |     at Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:74:9)
nftapi_1    |     at async Promise.all (index 4)
nftapi_1    |     at InstanceLoader.createInstancesOfProviders (/app/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
nftapi_1    |     at /app/node_modules/@nestjs/core/injector/instance-loader.js:29:13
nftapi_1    |     at async Promise.all (index 10)
nftapi_1    |     at InstanceLoader.createInstances (/app/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
nftapi_1    |     at InstanceLoader.createInstancesOfDependencies (/app/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
`

I am using HDWalletProvider as before,

**Comment by sunwrobert** [comment]
can you upgrade HDWallet provider?

**Comment by MetalGear-cmd** [comment]
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
TypeError: supportedProvider.send.toString(...).replaceAll is not a function
    at Object.standardizeOrThrow (D:\Documents\Office\opensea-creatures-master\node_modules\@0x\web3-wrapper\node_modules\@0x\utils\src\provider_utils.ts:78:71)
    at new Web3Wrapper (D:\Documents\Office\opensea-creatures-master\node_modules\@0x\web3-wrapper\src\web3_wrapper.ts:157:40)
    at new WyvernProtocol (D:\Documents\Office\opensea-creatures-master\node_modules\wyvern-js\src\wyvernProtocol.ts:397:25)
    at new OpenSeaPort (D:\Documents\Office\opensea-creatures-master\node_modules\opensea-js\src\seaport.ts:214:9)
    at Object.<anonymous> (D:\Documents\Office\opensea-creatures-master\index.js:51:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

I get this error after v 3 update

**Comment by csidi90** [comment]
Yes I ugpraded all dependencies including sdk to latest version and get


nftapi_1    | TypeError: supportedProvider.send.toString(...).replaceAll is not a function
nftapi_1    |     at Object.standardizeOrThrow (/app/node_modules/@0x/web3-wrapper/node_modules/@0x/utils/src/provider_utils.ts:78:71)


now as well as the mentioned above.

**Comment by kolbis** [comment]
The below code fails

```
 const seaport = new OpenSeaPort(client.currentProvider, {
      networkName: Network.Main,
      apiKey: 'xxx'
  })
```

with error:
`supportedProvider.send.toString(...).replaceAll is not a function`

**Comment by allan-hb** [comment]
how to resolve the question?

**Comment by infoseckev** [comment]
same issue for me

**Comment by my9527** [comment]
switch  nodejs  to 16.x  should  fixed  it

**Comment by robertu7** [comment]
works now on `opensea-js@3.0.2` with Node.js v16.13.2, other deps:

```
    "@0x/assert": "^3.0.30",
    "@0x/subproviders": "6.6",
    "web3-provider-engine": "^16.0.3"
```

**Comment by allan-hb** [comment]
upgrade nodejs version to 16+




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProjectOpenSea/opensea-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月19日(星期六) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProjectOpenSea/opensea-js] Since Upgrade to 3.0.0  TypeError: supportedProvider.send.toString(...).replaceAll is not a function (Issue #430)





 
same issue for me

**Comment by pguardiario** [comment]
It would be great if this lib supported 12+. Is the core team not
interested in supporting < 16? Some clarity on that would be helpful.

**Comment by esteban-OpenSea** [comment]
@csidi90 , are you still having this issue? Did you try upgrading the nodejs version?

**Comment by csidi90** [comment]
I still have that issue, I am on the latest LTS node version

**Comment by esteban-OpenSea** [comment]
Did you try working with the versions @robertu7 mentioned? https://github.com/ProjectOpenSea/opensea-js/issues/430#issuecomment-1079803746

**Comment by bmayen** [comment]
Also seeing "DEPRECATED: Please use providerUtils.standardizeOrThrow() instead" on Node v16 LTS with following deps:

"@truffle/hdwallet-provider": "^2.0.7",
"opensea-js": "^3.0.2"

**Comment by 0xZoomEye** [comment]
Also had this problem with "opensea-js": "^3.0.4" and node 16.15.0/ 16.14.2

**Comment by esteban-OpenSea** [comment]
Wanted to follow up on this and see if folks are still running into this.

That's strange, other devs say that upgrading works for them: https://github.com/ProjectOpenSea/opensea-js/issues/431#issuecomment-1078575054

**Comment by kaiqiangh** [comment]
> Wanted to follow up on this and see if folks are still running into this.
> 
> That's strange, other devs say that upgrading works for them: [#431 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/431#issuecomment-1078575054)

I have the same issue (TypeError: supportedProvider.send.toString(...).replaceAll is not a function). I am runnign node 16.16 and opensea-js is 4.0.7. Any tips for that? Thanks.
